import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import { BulbIcon, LinkArrow } from '@/components/Icons'
import useThemeSwitcher from '@/components/hooks/useThemeSwitcher'
import { useTheme } from '@/context/ThemeContext'
import pic_bulboff from '../../public/images/profile/pic_bulboff.gif'
import pic_bulbon from '../../public/images/profile/pic_bulbon.gif'
import light from '../../public/images/profile/light.png'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/images/profile/image.png'
import { useEffect } from 'react'
// import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  const { mode } = useTheme();


  useEffect(() => {
    console.log("Mode changed:", mode);
  }, [mode]);
  
  console.log('mode',mode)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />      
      </Head>
     <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
      <Layout className='pt-0'>
         <div className="flex items-center justify-between w-full">
           <div className='w-9/12'>
             <Image src={profilePic} alt="ProfileImage" className='w-full h-auto'/>
           </div>
           <div className='w-9/12 flex flex-col items-center self-center'>
               <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-4xl !text-left'/>
               <p className='my-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
               Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
               <div className='flex items-center self-start mt-2'>
                <Link href='/ChaithanyaCV.pdf' target={'_blank'} className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light' download={true}>Resume <LinkArrow className={"w-6 ml-1"}/></Link>
                <Link href='mailto:chaithanyavr56@gmail.com' target={'_blank'} className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'>Contact</Link>
               </div>
            </div>
         </div> 
      </Layout>
      <HireMe />
      <div className='absolute right-0 bottom-12 inline-block w-72'>
        {/* <Image src={lightBulb} alt='LightbulbImage' className='w-full h-auto '/> */}
        {/* <div className='relative'> */}
        {/* <div className='absolute -inset-5 bg-yellow-400  blur rounded-full bottom-[3em]  '></div> */}
       
        {/* </div> */}

        {/* <BulbIcon className={"relative w-full h-auto dark:saturate-200"}/> */}
        {/* <Image src={pic_bulboff} alt='bulb' className='w-full h-auto' /> */}
        <div className='w-1/2'>
        <Image src={pic_bulboff} alt="bulb" className=' left-7 top-9'/>
        <Image src={light} alt="light" className='absolute inset-0 object-cover w-full h-full'/>
         
        </div>
      </div>
     </main>
    </>
  )
}
